// File generated by FlutterFire CLI.
// ignore_for_files: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoP4St3o-x1Gvaqk635op4pJ9dOH7WIIQ',
    appId: '1:838087878656:android:8e20a0192fde808c5990e5',
    messagingSenderId: '838087878656',
    projectId: 'testora-ee95f',
    storageBucket: 'testora-ee95f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhTgVm3pRBd2L5GAXuIQpcMN8vkw1M2p4',
    appId: '1:838087878656:ios:dd7848fec63979225990e5',
    messagingSenderId: '838087878656',
    projectId: 'testora-ee95f',
    storageBucket: 'testora-ee95f.firebasestorage.app',
    iosBundleId: 'com.testora.app.testora',
  );

}